name: Build Third-Party Dependencies and Ocean Android Apps

on:
  workflow_dispatch:
    inputs:
      abi:
        description: "ABI to build for"
        required: true
        default: "arm64-v8a"
        type: choice
        options:
          - arm64-v8a
          - armeabi-v7a
          - x86
          - x86_64
          - custom
      custom_abi:
        description: "Custom ABI (if 'custom' is selected)"
        required: false
        type: string
      build_config:
        description: "Build configuration (debug or release)"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release
      link_type:
        description: "Link type (static or shared)"
        required: true
        default: "static"
        type: choice
        options:
          - static
          - shared
      android_sdk_version:
        description: "Android SDK Version"
        required: false
        default: "android-35"
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Android SDK
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "build-tools;35.0.0" \
            "platforms;${{ inputs.android_sdk_version }}" \
            "ndk;27.0.12077973"

      - name: Restore Third-Party Dependencies Cache
        uses: actions/cache@v3
        with:
          path: ${HOME}/install_ocean_thirdparty
          key: thirdparty-${{ runner.os }}-${{ inputs.abi }}-${{ inputs.build_config }}
          restore-keys: |
            thirdparty-${{ runner.os }}-${{ inputs.abi }}-

      - name: Restore Ocean Android Libraries Cache
        uses: actions/cache@v3
        with:
          path: ${HOME}/install_ocean
          key: ocean-${{ runner.os }}-${{ inputs.abi }}-${{ inputs.build_config }}
          restore-keys: |
            ocean-${{ runner.os }}-${{ inputs.abi }}-

      - name: Set Environment Variables
        run: |
          export OCEAN_THIRDPARTY_PATH=${HOME}/install_ocean_thirdparty
          export OCEAN_INSTALL_PATH=${HOME}/install_ocean
          export OCEAN_DEVELOPMENT_PATH=${HOME}/ocean
          echo "OCEAN_THIRDPARTY_PATH=${OCEAN_THIRDPARTY_PATH}" >> $GITHUB_ENV
          echo "OCEAN_INSTALL_PATH=${OCEAN_INSTALL_PATH}" >> $GITHUB_ENV
          echo "OCEAN_DEVELOPMENT_PATH=${OCEAN_DEVELOPMENT_PATH}" >> $GITHUB_ENV

      - name: Debug Third-Party Cache
        run: ls -l ${OCEAN_THIRDPARTY_PATH}

      - name: Fix Permissions for Third-Party Directory
        run: |
          if [ -d "${OCEAN_THIRDPARTY_PATH}" ]; then
            sudo chmod -R 777 "${OCEAN_THIRDPARTY_PATH}"
          else
            echo "${OCEAN_THIRDPARTY_PATH} does not exist, skipping chmod."
          fi

      - name: Check if Third-Party Dependencies Exist
        id: check_thirdparty
        run: |
          if [ -d "${OCEAN_THIRDPARTY_PATH}" ] && [ "$(ls -A ${OCEAN_THIRDPARTY_PATH})" ]; then
            echo "THIRDPARTY_EXISTS=true" >> $GITHUB_ENV
          else
            echo "THIRDPARTY_EXISTS=false" >> $GITHUB_ENV
          fi
          echo "THIRDPARTY_EXISTS is set to: $THIRDPARTY_EXISTS"

      - name: Build Third-Party Dependencies (if not cached)
        if: env.THIRDPARTY_EXISTS == 'false'
        run: |
          ./build/cmake/build_thirdparty_android.sh \
            -c ${{ inputs.build_config }} \
            -l ${{ inputs.link_type }} \
            -b "${HOME}/build_ocean_thirdparty" \
            -i "${HOME}/install_ocean_thirdparty" \
            --abi ${{ inputs.abi }} \
            --sdk ${{ inputs.android_sdk_version }}

      - name: Cache Third-Party Dependencies
        uses: actions/cache@v3
        with:
          path: ${HOME}/install_ocean_thirdparty
          key: thirdparty-${{ runner.os }}-${{ inputs.abi }}-${{ inputs.build_config }}

      - name: Check if Ocean Android Libraries Exist
        id: check_ocean_lib
        run: |
          if [ -d "${OCEAN_INSTALL_PATH}" ] && [ "$(ls -A ${OCEAN_INSTALL_PATH})" ]; then
            echo "OCEAN_LIB_EXISTS=true" >> $GITHUB_ENV
          else
            echo "OCEAN_LIB_EXISTS=false" >> $GITHUB_ENV
          fi
          echo "OCEAN_LIB_EXISTS is set to: $OCEAN_LIB_EXISTS"

      - name: Build Ocean Android Libraries (if not cached)
        if: env.OCEAN_LIB_EXISTS == 'false'
        shell: bash
        run: |
          ./build/cmake/build_ocean_android.sh \
            -c ${{ inputs.build_config }} \
            -l ${{ inputs.link_type }} \
            -b "${HOME}/build_ocean" \
            -i "${HOME}/install_ocean" \
            -t "${HOME}/install_ocean_thirdparty" \
            --abi ${{ inputs.abi }} \
            --sdk ${{ inputs.android_sdk_version }}

      - name: Cache Ocean Android Libraries
        uses: actions/cache@v3
        with:
          path: ${HOME}/install_ocean
          key: ocean-${{ runner.os }}-${{ inputs.abi }}-${{ inputs.build_config }}

      - name: Build and Upload Android Apps Sequentially
        run: |
          export OCEAN_DEVELOPMENT_PATH=${HOME}/ocean
          # In this example, we're building the "demo/base/console" app as described in the docs.
          APP_DIR="$OCEAN_DEVELOPMENT_PATH/build/gradle/application/ocean/demo/base/console/android"
          if [ -d "$APP_DIR" ]; then
            cd "$APP_DIR"
            ./gradlew build
            cp app/build/outputs/apk/debug/app-debug.apk ocean_demo_base_console_debug.apk
            cp app/build/outputs/apk/release/app-release.apk ocean_demo_base_console_release.apk
            gh run upload-artifact --name ocean_demo_base_console_debug_apk --path ocean_demo_base_console_debug.apk
            gh run upload-artifact --name ocean_demo_base_console_release_apk --path ocean_demo_base_console_release.apk
          else
            echo "Skipping demo/base/console as directory does not exist."
          fi
